### ISSUE TITLE
handle nested subdirectories

### ISSUE THREAD

**Issue by monfortm** [alexsavio/hansel#20]
Hi Alexsavio,

I like the lib it's clean and works well.
I was wondering if this could work

Got internal and external data. Internal data is all mine. External data is associated with a known source, but the whole set of subfolder is common. e.g. 

> root_dir/myData/subject1/tissue1 [...]
> root_dir/myData/subject1/tissue2 [...]
> root_dir/externalData/source1/subject1/tissue1 [...]
> root_dir/externalData/source1/subject1/tissue2 [...]
> root_dir/externalData/source2/subject1/tissue1 [...]
> root_dir/externalData/source2/subject1/tissue2 [...]

```
── root_dir
   ├── myData
   │     └── subject1
   │            ├── tissue1
   │            └── tissue2
   │      
   └── externalData
         ├── source1
         │     └── subject1
         │            ├── tissue1
         │            └── tissue2
         └── source2
               └── subject1
                      ├── tissue1
                      └── tissue2
```
Basically, i need to handle external_Data/sourceX as one layer, like myData. You know what I mean ?

Do you reckon there is an easy way to do so ?
I tried so far to make the structure with mktree and it works well, i.e. with the following values_map

```
values_map = {
        'sources':  ['myData', 'externalData/source1', 'externalData/source2'],
        'subject': ['subject1', 'subject2'],
}
```

But when using crumbs later, the subfolder information is lost and **external data sources** 1 and 2 are treated as **myData subjects**. (NB: is what I'm saying even clear?). 

I still did not manage to keep this information sublayer even with a regex containing a slash ( something in the lines of '^.*Data(/source1|/source2|)$' )

Thanks for the help.
Great lib ;)

Cheers!

Matthias M.

**Comment by alexsavio** [comment]
Hi Matthias,

Thanks for the message. :)

I see your problem. You have the 'subject' folders in **myData** and **external resources** in different relative depths, because you have the extra 'source' level in the **external resources**. What if you added one level to your **myData** folder? For example:

```
cd myData
mkdir processed
mv subject* processed/
```
Is this an option for you?

Another option would be to use one (either **myData** or **external resources**) as a reference Crumb and use it to fill the other Crumb when you need to access the other folder. A quick example with a loop would be:

```
external_cr = Crumb('<base_dir>/externalData/{source}/{subject}/{tissue}')
mydata_cr = Crumb('<base_dir>/myData/{subject}/{tissue}')

def fill_crumb(src_cr, dest_cr, fields):
    my_cr = dest_cr.copy()
    for field in fields:
        my_cr[field] = dest_cr[field][0]
    return dest_cr

get_mydata_tissue_cr = lambda src, dst: fill_crumb(src, dst, fields=['subject', 'tissue'])

for ecr in external_cr.ls('tissue'):
    mydata_tissue_cr = get_mydata_tissue_cr(ecr, mydata_cr)
```

I hope this helps.

**Comment by alexsavio** [comment]
What you are trying to achieve by adding the slash in one crumb argument won't work, since when Crumb starts looking inside the file system it will totally ignore the slash and try to fit it in the path.

In fact you just gave me a new feature idea, I wonder how would be the best way to implement that.

**Comment by monfortm** [comment]
Hi Alexsavio, Thanks for the quick answer!

So, your first solution is not a possibility for me. We are talking here about a structure that I share with other people, and on which a piece of my code relies. Not that it's not possible to update the code, but since other people than me also fish files from that structure, I basically do not want to break all their symlinks ! The second solution seems to be what I'd need. Need to understand it better and try it myself.

I'd like to integrate your lib to my code since it seems to do a great job. However, I'm just trying it for now and see if it fits all my use cases

Anyway thank you, I am happy about the new feature idea :) I don't know what's the best way for this implementation neither. Maybe a dedicated key work in the crumb prototype e.g. 
Crumb( '{base_dir}/{stuff}/{**variablesublayers**::stuff2}/{stuff3}' )... well not sure this make sense, since I did not read your code :)

Cheers

**Comment by alexsavio** [comment]
Sure, please let me know if my example works for you. It is copying the crumb arguments from one Crumb to the other. It's how I work with it when I have subject data hanging from different folders. I use one as an index.

**Comment by alexsavio** [comment]
Hi @GingerWare,
I'm sorry, it has been some time that I haven't touched this project. 
Another way to do it, going back to my example, if `mydata_cr` and `external_cr` have the same crumb arguments, you can use the `arg_values` property and the `update` function:

```
for ecr in external_cr.ls('tissue'):
    mydata_cr.update(**ecr.arg_values)
```
This would fill up the `mydata_cr` crumb arguments with the values in `ecr`.

**Comment by monfortm** [comment]
Thanks for the input @alexsavio 
I'll give it another try!

Cheers and thanks for the good work!
M.
